

class AppAppearance():
	PIPELINE_TITLE_COLOR = "#040404" 
	PIPELINE_HOVER_COLOR = "#787878"
	PIPELINE_BACKGROUND_COLOR = "#D6D6D6"
	PIPELINE_NOT_HOVER_COLOR = "#E2E2E2"
	PIPELINE_HOLDER_BORDER_COLOR = PIPELINE_BACKGROUND_COLOR
	PIPELINE_PREPROCESSOR_BACKGROUND_COLOR = PIPELINE_BACKGROUND_COLOR

	# Draggable Columns
	DRAGGABLE_COLUMN_COLOR = "#333333"
	DRAGGABLE_COLOMN_BORDER_COLOR = "#040404"
	LINEAR_COLOR = "#57BDAC"
	ENSEMBLE_COLOR = "#241C72"
	TREE_COLOR = "#234234"
	NEURAL_COLOR = "#235235"
	PREPROCESSOR_COLOR = "#DD6A34"
	PREPROCESSOR_BORDER_COLOR = "#DD6A34"
	VALIDATOR_COLOR = "#8D064E"