

class AppAppearance():
	PIPELINE_TITLE_COLOR = "#040404" 
	PIPELINE_HOVER_COLOR = "#8F8F8F"
	PIPELINE_BACKGROUND_COLOR = "#C3C3C3"
	PIPELINE_NOT_HOVER_COLOR = "#E2E2E2"
	PIPELINE_HOLDER_BORDER_COLOR = PIPELINE_BACKGROUND_COLOR
	PIPELINE_PREPROCESSOR_BACKGROUND_COLOR = PIPELINE_BACKGROUND_COLOR

	# Draggable Columns
	DRAGGABLE_COLUMN_COLOR = "#0C1990"
	DRAGGABLE_COLOMN_BORDER_COLOR = "#040404"
	
	# REGRESSORS
	REGRESSOR_LINEAR_COLOR = "#ffa600"
	REGRESSOR_ENSEMBLE_COLOR = "#ff8531"
	REGRESSOR_TREE_COLOR = "#ff6361"
	REGRESSOR_NEURAL_COLOR = "#de5a79"

	# CLASSIFIERS
	CLASSIFIER_LINEAR_COLOR = "#476EAE"
	CLASSIFIER_ENSEMBLE_COLOR = "#48B3AF"
	CLASSIFIER_TREE_COLOR = "#72DD59"
	CLASSIFIER_NEURAL_COLOR = "#02A376"

#"#009663ff"
#"#72DD59"
	PREPROCESSOR_COLOR = "#5D0F91"
	PREPROCESSOR_BORDER_COLOR = "#5D0F9D"
	VALIDATOR_COLOR = "#068D41"

	